config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'

  devise_scope :user do
 get "/signup" => "devise/registrations#new", as: "new_user_registration"
    end
 devise_for :users, skip: [:sessions] #,:controllers => {:registrations => "registrations"}
 as :user do

     get 'login' => 'devise/sessions#new', :as => :new_user_session
     post 'login' => 'devise/sessions#create', :as => :user_session
     match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
           :via => Devise.mappings[:user].sign_out_via
 end
  get 'password_resets/new'

  get 'password_resets/edit'

  authenticated :user do
  #  get '/home', to: 'pages#home', as: :authenticated_root
   root 'pages#home', as: :authenticated_root
  end
  root 'pages#index'
  get 'upload' => 'pages#upload'
  get 'subscribe' => 'pages#subscribe'
  resources :subscribes, only: [:create, :new]
  get 'browser'=> 'pages#browser'
  get 'about' => 'pages#about'
  get 'winners' => 'pages#winner'
  get 'token' => 'password_resets#token'
  post 'find_token' => 'password_resets#find_token'
  get ':username' => 'pages#profile', as: :user
  get "/fetch_selfie/:id" => 'selfies#show', as: 'fetch_selfy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :selfies do
    resource :like, module: :selfies
    resources :comments, module: :selfies
    # member do
    #   get "like", to: "selfies#like", via: :post
    #
    #   delete "unlike", to: "selfies#unlike"
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="notice red darken-4">
        The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li class="notice red"><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/shared/_leaderboard.html.erb
<% unless @week_trendings.empty?  %>

<div class="leaderboard">
  <div class="grid-title">
    <h2 class="grid-title-text">
      Trending
    </h2>
  </div>
  <div class="main-carousel main-carousel__card">
    <% @week_trendings.each do |trending| %>
    <div class="carousel-cell card-trending">
        <div class="">

            <div class="card-main">
              <%= link_to fetch_selfy_path(trending.id), class: "show_lightbox", data: { featherlight: "mylightbox" }, remote: true do %>

                <img class="card-main-image" src="<%= trending.photo.url if trending.photo.url  %>" alt="Image Alt text">
              <% end %>

                <!-- add class liked for image like by current user -->
            </div>
            <!-- .card-main -->

            <!-- .card-footer -->
        </div>
        <!-- .carousel ending -->
        </div>

    <% end %>



  </div>

</div>
<% end %>

app/views/shared/_selfies.html.erb
<div class="lightbox" id="lightbox">
    <%=render partial: "selfies/show", locals: { selfie: @selfie }  %>
</div>
<% @selfies.each do |selfie| %>
<div class="card ">

    <div class="card-main">

    <%= link_to fetch_selfy_path(selfie.id), class: "show_lightbox", data: { featherlight: "mylightbox" }, remote: true do %>

      <img class="card-main-image" src="<%= selfie.photo.url if selfie.photo.url  %>" alt="Image Alt text">
    <% end %>



        </a>
        <div id="<%= selfie.id%>_likes">
            <%= render  partial: "selfies/likes/likes", locals: { selfie: selfie} %>
        </div>
        <!-- add class liked for image like by current user -->
    </div>
    <!-- .card-main -->
    <div class="card-footer">
        <div class="card-footer-avatar">
          <%= link_to  user_path(selfie.user.username) do %>
          <%= gravatar_for selfie.user %>
          <% end %>
        </div>
        <!-- .card-footer-avater -->
        <div class="card-footer-text">
            <a href="#" class="card-footer-title">  <%= link_to selfie.user.username,  user_path(selfie.user.username)  %></a>
            <div class="card-footer-info">

                <div class="card-footer-likes" id="<%= selfie.id %>_counter"><%= selfie.likes.count %></div>
                <a href="#" class="card-footer-views"><%= selfie.impressionist_count %></a>
            </div>
            <!-- .card-footer-info -->

        </div>
        <!-- .card-footer-text -->
    </div>
    <!-- .card-footer -->
</div>
<!-- .card -->
<% end %>