config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'

  devise_scope :user do
 get "/signup" => "devise/registrations#new", as: "new_user_registration"
    end
 devise_for :users, skip: [:sessions] #,:controllers => {:registrations => "registrations"}
 as :user do

     get 'login' => 'devise/sessions#new', :as => :new_user_session
     post 'login' => 'devise/sessions#create', :as => :user_session
     match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
           :via => Devise.mappings[:user].sign_out_via
 end
  get 'password_resets/new'

  get 'password_resets/edit'

  authenticated :user do
  #  get '/home', to: 'pages#home', as: :authenticated_root
   root 'pages#home', as: :authenticated_root
  end
  root 'pages#index'
  get 'upload' => 'pages#upload'
  get 'subscribe' => 'pages#subscribe'
  resources :subscribes, only: [:create, :new]
  get 'browser'=> 'pages#browser'
  get 'about' => 'pages#about'
  get 'winners' => 'pages#winner'
  get 'token' => 'password_resets#token'
  post 'find_token' => 'password_resets#find_token'
  get ':username' => 'pages#profile', as: :user
  get "/fetch_selfie/:id" => 'selfies#show', as: 'fetch_selfy'
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :selfies do
    resource :like, module: :selfies
    resources :comments, module: :selfies
    # member do
    #   get "like", to: "selfies#like", via: :post
    #
    #   delete "unlike", to: "selfies#unlike"
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
        <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body class="">
        <header class="header">
            <div class="header-container">
                <a href="/" class="logo">SelfieStar</a>
                <ul class="menu">
                <% if current_user.try(:admin?) %>
                    <%= link_to "Dashboard", admin_dashboard_path, class: "dash_link" %>
                <% end %>
                    <li>
                      <%= link_to "Upload", upload_path, class: "upload_link" %>

                    </li>
                    <% if user_signed_in? %>
                    <li>
                      <%= link_to "Profile", user_path(current_user.username), class: "profile_link" %>

                    </li>
                    <li>
                      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "signout_link" %>

                    </li>
                <% else %>

                    <li><%= link_to "Sign Up", new_user_registration_path, class: "signup_link" %></li>
                    <li><%= link_to "Sign In", new_user_session_path, class: "signin_link" %></li>
                    <% end %>

                </ul>
            </div>

        </header>
        <%= flash_messages %>
        <main class="main">
            <%= yield %>
        </main>
        <footer class="footer">
            <div class="footer_container">
                <div class="footer_section">
                    <h4>SelfieStar</h4>
                    <ul class="footer_menu">
                        <li><a href="/about">About</a></li>
                        <li><%= link_to "winners", winners_path %></li>

                    </ul>
                </div>
                <div class="footer_section">
                    <h4>SocialStar</h4>
                    <ul class="footer_menu">
                        <li><a href="#facebook">Facebook</a></li>
                        <li><a href="#instagram">Instagram</a></li>
                        <li><a href="#snapchat">Snapchat</a></li>
                        <li><a href="#twitter">Twitter</a></li>
                    </ul>
                </div>
                <div class="footer_section">
                    <div class="partner-grid">
                      <%= image_tag('afripay.jpg',  class: 'partner' )%>
                      <%= image_tag('qodoo.png',  class: 'partner' )%>

                    </div>
                </div>
                <div class="footer_section">
                    <div class="masthead">
                        <a class="footer_logo" href="/"></a>
                        <ul class="masthead_section">
                            <li>Copyright &copy; <%= Time.now.strftime("%Y") %> </li>
                            <li>SelfieStar</li>
                        </ul>
                        <ul class="masthead_section">
                            <li>Made in the Gambia</li>
                            <li>Powered by <a href="https://www.gcubed.gm">GCubed</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>

    </body>
</html>